version: '3'

services:
  rr-services:
    image: rr-services
    build: .
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    depends_on:
      - db
    
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root_12345
  