version: '3'

services:
  rr-services:
    image: rr-services
    build: .
    environment:
      NODE_ENV: production
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
    command: yarn run start:server
    depends_on:
      - db
  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root_12345
    volumes:
      - mongodata:/data/db
volumes:
  mongodata:
  